export enum AINumericConstantName {
  IN_FRAME_VISIBLITY_THRESHOLD = 'IN_FRAME_VISIBLITY_THRESHOLD',
  STILLNESS_LOWER_THRESHOLD_M = 'STILLNESS_LOWER_THRESHOLD_M',
  STILLNESS_THRESHOLD_M = 'STILLNESS_THRESHOLD_M',
  STILLNESS_Z_AXIS_PERCENTAGE_THRESHOLD = 'STILLNESS_Z_AXIS_PERCENTAGE_THRESHOLD',
  STILLNESS_THRESHOLD_WHILE_RECORDING_M = 'STILLNESS_THRESHOLD_WHILE_RECORDING_M',
  STILLNESS_DETECTION_WINDOW_DURING_RECORDING_S = 'STILLNESS_DETECTION_WINDOW_DURING_RECORDING_S',
  FACING_CAMERA_VISIBLITY_THRESHOLD = 'FACING_CAMERA_VISIBLITY_THRESHOLD',
  STILLNESS_COUNTDOWN_DURATION_S = 'STILLNESS_COUNTDOWN_DURATION_S',
  MIN_TIME_PASSED_TO_DETECT_STILLNESS_S = 'MIN_TIME_PASSED_TO_DETECT_STILLNESS_S',

  // Nod detection
  NOD_DETECTION_BUFFER_DURATION_S = 'NOD_DETECTION_BUFFER_DURATION_S',
  Y_POS_HELPER_M = 'Y_POS_HELPER_M',

  // Head shake
  HEAD_SHAKE_DETECTION_BUFFER_DURATION_S = 'HEAD_SHAKE_DETECTION_BUFFER_DURATION_S',
  HEAD_SHAKE_ANGLE_THRESHOLD_DEGREES = 'HEAD_SHAKE_ANGLE_THRESHOLD_DEGREES',

  // Jitter detection
  MIN_KEYPOINTS_FOR_JITTER_DETECTION = 'MIN_KEYPOINTS_FOR_JITTER_DETECTION',
  JITTER_DETECTION_WINDOW_S = 'JITTER_DETECTION_WINDOW_S',
  TIME_BETWEEN_MODEL_RELOAD_S = 'TIME_BETWEEN_MODEL_RELOAD_S',

  KEYPOINT_BUFFER_DURATION_MS = 'KEYPOINT_BUFFER_DURATION_MS',
  CLOSE_ENOUGH_TO_START_VALUE_RATIO = 'CLOSE_ENOUGH_TO_START_VALUE_RATIO',
  HIGH_FPS_THRESHOLD = 'HIGH_FPS_THRESHOLD',

  // Extremum detection
  MIN_FRAMES_FOR_EXTREMUM = 'MIN_FRAMES_FOR_EXTREMUM',
  MIN_TIME_FOR_EXTREMUM_S = 'MIN_TIME_FOR_EXTREMUM_S',

  // Rep start
  PRE_WINDOW_FRAMES_REP_START = 'PRE_WINDOW_FRAMES_REP_START',
  MAX_LOOKBACK_REP_START_S = 'MAX_LOOKBACK_REP_START_S',
  KEEP_KEYPOINT_HISTORY_DURING_RECORDING_MS = 'KEEP_KEYPOINT_HISTORY_DURING_RECORDING_MS',
  REP_START_END_VELOCITY_HIGH_FPS_M_PER_S = 'REP_START_END_VELOCITY_HIGH_FPS_M_PER_S',
  REP_START_END_VELOCITY_LOW_FPS_M_PER_S = 'REP_START_END_VELOCITY_LOW_FPS_M_PER_S',
  REP_START_VELOCITY_SUSTAIN_S = 'REP_START_VELOCITY_SUSTAIN_S',
  REP_START_CONSECUTIVE_FRAMES_UNDER_VELOCITY_THRESHOLD_S = 'REP_START_CONSECUTIVE_FRAMES_UNDER_VELOCITY_THRESHOLD_S',
  REP_START_JOINT_STILLNESS_VELOCITY_THRESHOLD_M_PER_S = 'REP_START_JOINT_STILLNESS_VELOCITY_THRESHOLD_M_PER_S',

  // Rep end
  REP_END_VELOCITY_M_PER_S = 'REP_END_VELOCITY_M_PER_S',
  REP_END_LOOKBACK_S = 'REP_END_LOOKBACK_S',

  // Time at extremum
  TIME_AT_EXTREMUM_VELOCITY_THRESHOLD_M_PER_S = 'TIME_AT_EXTREMUM_VELOCITY_THRESHOLD_M_PER_S',
  TIME_AT_EXTREMUM_VELOCITY_SUSTAIN_S = 'TIME_AT_EXTREMUM_VELOCITY_SUSTAIN_S',

  // Detection end
  MIN_STILL_TIME_TO_STOP_DETECTION_S = 'MIN_STILL_TIME_TO_STOP_DETECTION_S',
}
