export enum KeypointId {
  NOSE = 'nose',
  LEFT_EYE_INNER = 'left_eye_inner',
  LEFT_EYE = 'left_eye',
  LEFT_EYE_OUTER = 'left_eye_outer',
  RIGHT_EYE_INNER = 'right_eye_inner',
  RIGHT_EYE = 'right_eye',
  RIGHT_EYE_OUTER = 'right_eye_outer',
  LEFT_EAR = 'left_ear',
  RIGHT_EAR = 'right_ear',
  MOUTH_LEFT = 'mouth_left',
  MOUTH_RIGHT = 'mouth_right',
  LEFT_SHOULDER = 'left_shoulder',
  RIGHT_SHOULDER = 'right_shoulder',
  LEFT_ELBOW = 'left_elbow',
  RIGHT_ELBOW = 'right_elbow',
  LEFT_WRIST = 'left_wrist',
  RIGHT_WRIST = 'right_wrist',
  PINKY_KNUCKLE_LEFT = 'pinky_knuckle_left',
  PINKY_KNUCKLE_RIGHT = 'pinky_knuckle_right',
  INDEX_KNUCKLE_LEFT = 'index_knuckle_left',
  INDEX_KNUCKLE_RIGHT = 'index_knuckle_right',
  THUMB_KNUCKLE_LEFT = 'thumb_knuckle_left',
  THUMB_KNUCKLE_RIGHT = 'thumb_knuckle_right',
  LEFT_HIP = 'left_hip',
  RIGHT_HIP = 'right_hip',
  LEFT_KNEE = 'left_knee',
  RIGHT_KNEE = 'right_knee',
  LEFT_ANKLE = 'left_ankle',
  RIGHT_ANKLE = 'right_ankle',
  LEFT_HEEL = 'left_heel',
  RIGHT_HEEL = 'right_heel',
  LEFT_FOOT_INDEX = 'left_foot_index',
  RIGHT_FOOT_INDEX = 'right_foot_index',
}

export enum KeypointIdYoloV11 {
  NOSE = 'nose',
  LEFT_EYE = 'left_eye',
  RIGHT_EYE = 'right_eye',
  LEFT_EAR = 'left_ear',
  RIGHT_EAR = 'right_ear',
  LEFT_SHOULDER = 'left_shoulder',
  RIGHT_SHOULDER = 'right_shoulder',
  LEFT_ELBOW = 'left_elbow',
  RIGHT_ELBOW = 'right_elbow',
  LEFT_WRIST = 'left_wrist',
  RIGHT_WRIST = 'right_wrist',
  LEFT_HIP = 'left_hip',
  RIGHT_HIP = 'right_hip',
  LEFT_KNEE = 'left_knee',
  RIGHT_KNEE = 'right_knee',
  LEFT_ANKLE = 'left_ankle',
  RIGHT_ANKLE = 'right_ankle',
}
