import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import React from 'react'
import {AppRouterCacheProvider} from '@mui/material-nextjs/v13-appRouter'
import {ThemeProvider} from '@mui/material'
import {theme} from '@/util/theme'
import {Toaster} from 'react-hot-toast'
import {AuthProvider} from '@/context/auth-provider'
import { AppProvider } from '@/context/app-provider';
import { LocalizationProvider } from '@mui/x-date-pickers';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" style={{scrollBehavior: 'smooth'}}>
        <body className={inter.className}>
        <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
                <AppProvider>
                    <AuthProvider>
                        {children}
                    </AuthProvider>
                </AppProvider>
            </ThemeProvider>
        </AppRouterCacheProvider>

        <Toaster/>
        </body>
        </html>
    )
}
