export enum FirestoreCollection {
  COMPONENT = 'component',
  EXERCISE = 'exercise',
  EXERCISE_ATTRIBUTE = 'exercise-attribute',
  EXERCISE_ATTRIBUTE_VALUE = 'exercise-attribute-value',
  GROUP = 'group',
  SUBGROUP = 'subgroup',
  CYCLE = 'cycle',
  TRAINING = 'training',
  TRAINING_COMPONENT = 'component',
  TRAINING_EXERCISE = 'exercise',
  SET_GROUP = 'set',
  SET_SUB_GROUP = 'set-sub-group',
  SET_EXERCISE = 'set-exercise',
  EXERCISE_INFO = 'exercise-info',
  SUPER_EXERCISE_INFO = 'super-exercise-info',
  WELLNESS = 'wellness',
}