import { POSE_LANDMARKS } from '@mediapipe/pose';

export const POINT_FILL_COLOR = '#D3D3D3';
export const POINT_OUTLINE_COLOR = '#1F51FF';

export const IMPORTANT_KEYPOINTS = [
    POSE_LANDMARKS.LEFT_SHOULDER,
    POSE_LANDMARKS.RIGHT_SHOULDER,
    POSE_LANDMARKS.LEFT_ELBOW,
    POSE_LANDMARKS.RIGHT_ELBOW,
    POSE_LANDMARKS.LEFT_WRIST,
    POSE_LANDMARKS.RIGHT_WRIST,
    POSE_LANDMARKS.LEFT_HIP,
    POSE_LANDMARKS.RIGHT_HIP,
    POSE_LANDMARKS.LEFT_KNEE,
    POSE_LANDMARKS.RIGHT_KNEE,
    POSE_LANDMARKS.LEFT_ANKLE,
    POSE_LANDMARKS.RIGHT_ANKLE,
    POSE_LANDMARKS.LEFT_HEEL,
    POSE_LANDMARKS.RIGHT_HEEL,
    POSE_LANDMARKS.LEFT_FOOT_INDEX,
    POSE_LANDMARKS.RIGHT_FOOT_INDEX
];

