export const POSE_DETECTION_CONSTRAINTS = {
  MIN_KEYPOINTS_IN_FRAME: 26,
  IN_FRAME_VISIBLITY_THRESHOLD: 0.2,
  STILLNESS_THRESHOLD: 0.025, // in meters
  STILLNESS_THRESHOLD_WHILE_READY: 0.04, // in meters
  FACING_CAMERA_VISIBLITY_THRESHOLD: 0.5,
};
