version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app  # Sync the current directory with the container
      - /app/node_modules  # Exclude node_modules from being overwritten by the volume
    command: npm run start:prod
