export enum MainSet {
  BLOCK = 'Block', // complete 1st set of 1st exercise, 1st set of 2nd exercise, ...
  CIRCUIT = 'Circuit', // complete all sets of 1st exercise, all sets of 2nd exercise, ...
}
