import type { Attribute } from '@/controller/attribute/type/attribute.type';

export const Equipment: Attribute[] = [
  {
    field: 'cardio',
    name: 'Cardio Equipment',
    options: [
      { field: 'treadmill', name: 'Treadmill' },
      { field: 'elliptical-trainer', name: 'Elliptical Trainer' },
      { field: 'stationary-bike', name: 'Stationary Bike' },
      { field: 'rowing-machine', name: 'Rowing Machine' },
      { field: 'stair-climber-stepper', name: 'Stair Climber/Stepper' },
      { field: 'spin-bike', name: 'Spin Bike' },
      { field: 'air-bike', name: 'Air Bike' },
      { field: 'arc-trainer', name: 'Arc Trainer' },
    ],
  },
  {
    field: 'strength',
    name: 'Strength Training Equipment',
    options: [
      {
        field: 'barbells',
        name: 'Barbells',
        options: [
          { field: 'olympic', name: 'Olympic Barbell' },
          { field: 'trapbar', name: 'Trapbar' },
          { field: 'ez-bar', name: 'EZ Curl Bar' },
        ],
      },
      {
        field: 'dumbbells',
        name: 'Dumbbells',
        options: [
          { field: 'regular', name: 'Fixed Dumbbells' },
          { field: 'adjustable', name: 'Adjustable Dumbbells' },
        ],
      },
      { field: 'kettlebells', name: 'Kettlebells' },
      {
        field: 'weight-plates',
        name: 'Weight Plates',
        options: [
          { field: 'standard', name: 'Standard' },
          { field: 'bumper', name: 'Bumper Plates' },
        ],
      },
      {
        field: 'bench',
        name: 'Bench',
        options: [
          { field: 'flat', name: 'Flat Bench' },
          { field: 'incline', name: 'Adjustable/Incline Bench' },
          { field: 'decline', name: 'Decline Bench' },
        ],
      },
      { field: 'power-rack', name: 'Power Rack/Squat Rack' },
      { field: 'smith', name: 'Smith Machine' },
      { field: 'cable', name: 'Cable Machine' },
      { field: 'functional-trainer', name: 'Functional Trainer' },
      { field: 'lat-pulldown', name: 'Lat Pulldown Machine' },
      { field: 'cable-crossover', name: 'Cable Crossover Machine' },
      { field: 'leg-press', name: 'Leg Press Machine' },
      { field: 'hack-squat', name: 'Hack Squat Machine' },
      { field: 'leg-curl', name: 'Leg Extension/Leg Curl Machine' },
      { field: 'preacher-curl-bench', name: 'Preacher Curl Bench' },
      { field: 'chest-press', name: 'Chest Press Machine' },
      { field: 'shoulder-press', name: 'Shoulder Press Machine' },
      { field: 'pec-deck', name: 'Pec Deck Machine' },
      { field: 'seated-row', name: 'Seated Row Machine' },
      { field: 'abdominal-crunch', name: 'Abdominal Crunch Machine' },
      { field: 'back-extension-bench', name: 'Back Extension Bench' },
      { field: 'flywheel', name: 'Flywheel' },
      { field: 'technogym', name: 'Technogym' },
    ],
  },
  {
    field: 'free-weight',
    name: 'Free Weight Accessories',
    options: [
      { field: 'weightlifting-belt', name: 'Weightlifting Belt' },
      { field: 'lifting-straps', name: 'Lifting Straps' },
      { field: 'weightlifting-gloves', name: 'Weightlifting Gloves' },
      { field: 'foam-roller', name: 'Foam Roller' },
      { field: 'resistance-bands', name: 'Resistance Bands' },
      { field: 'medicine-ball', name: 'Medicine Ball' },
      { field: 'slam-ball', name: 'Slam Ball' },
      { field: 'battle-ropes', name: 'Battle Ropes' },
      { field: 'sandbags', name: 'Sandbags' },
      { field: 'power-band', name: 'Power Band' },
      { field: 'external-load', name: 'External Load' },
    ],
  },
  {
    field: 'bodyweight',
    name: 'Bodyweight Equipment',
    options: [
      { field: 'pull-up-bar', name: 'Pull-Up Bar' },
      { field: 'dip-station', name: 'Dip Station' },
      { field: 'gymnastic-rings', name: 'Gymnastic Rings' },
      { field: 'parallettes', name: 'Parallettes' },
      { field: 'push-up-bars', name: 'Push-Up Bars' },
      { field: 'ab-wheel', name: 'Ab Wheel' },
    ],
  },
  {
    field: 'functional',
    name: 'Functional Training Equipment',
    options: [
      { field: 'trx', name: 'TRX Suspension Trainer' },
      { field: 'plyo-box', name: 'Plyo Box (Plyometric Box)' },
      { field: 'jump-rope', name: 'Jump Rope' },
      { field: 'agility-ladder', name: 'Agility Ladder' },
      { field: 'bosu-ball', name: 'BOSU Ball' },
      { field: 'stability-ball', name: 'Stability Ball' },
      { field: 'balance-board', name: 'Balance Board' },
      { field: 'keiser', name: 'Keiser' },
      { field: 'harness', name: 'Harness' },
      { field: 'partner', name: 'Partner' },
      { field: 'box', name: 'Box' },
      { field: 'hurdle', name: 'Hurdle' },
      { field: 'stick', name: 'Stick' },
      { field: 'water-bag', name: 'Water Bag' },
    ],
  },
  {
    field: 'specialty',
    name: 'Specialty Machines',
    options: [
      { field: 'smith', name: 'Smith Machine' },
      { field: 'glute-ham-developer', name: 'Glute Ham Developer (GHD)' },
      { field: 't-bar-row', name: 'T-Bar Row Machine' },
      { field: 'chest-fly', name: 'Chest Fly Machine' },
      { field: 'seated-calf-raise', name: 'Seated Calf Raise Machine' },
      { field: 'dip-station', name: 'Vertical Knee Raise/Dip Station' },
      { field: 'iso-belt', name: 'Iso Belt' },
    ],
  },
  {
    field: 'miscellaneous',
    name: 'Miscellaneous Equipment',
    options: [
      { field: 'gym-timer-clock', name: 'Gym Timer/Clock' },
      { field: 'sound-system', name: 'Sound System' },
      { field: 'flooring-mats', name: 'Flooring Mats' },
      { field: 'water-fountain-cooler', name: 'Water Fountain/Cooler' },
      { field: 'towel-rack', name: 'Towel Rack' },
      { field: 'mirrors', name: 'Mirrors' },
    ],
  },
  {
    field: 'football',
    name: 'Football Equipment',
    options: [
      { field: 'balls', name: 'Balls' },
      { field: 'marks', name: 'Marks' },
      { field: 'bibs', name: 'Bibs' },
      { field: 'sticks', name: 'Sticks' },
      { field: 'mannequins', name: 'Mannequins' },
    ],
  },
];
