export const DASHBOARD_MAIN_VIEW = 'mainView';
export const DASHBOARD_GROUPS_VIEW = 'athletes';
export const DASHBOARD_ADD_INSTITUTION_VIEW = 'addInstitution';
export const DASHBOARD_REGISTER_USERS_VIEW = 'registerUsers';

export const DASHBOARD_VIEWS = [
  DASHBOARD_MAIN_VIEW,
  DASHBOARD_GROUPS_VIEW,
  DASHBOARD_ADD_INSTITUTION_VIEW,
  DASHBOARD_REGISTER_USERS_VIEW,
] as const;
