export enum FirestoreCollection {
  LOCAL_DEV = 'local-dev',
  USER = 'users',
  COMPONENT = 'components',
  ATTRIBUTE = 'attributes',
  EXERCISE = 'exercises',
  EXERCISE_ATTRIBUTE_VALUES = 'exerciseAttributeValues',
  WELLNESS = 'wellness',
  GROUP = 'groups',
  SUBGROUP = 'subgroups',
  TRAINING = 'trainings',
  INSTITUTION = 'institutions',
  METHOD = 'methods',
  TRAINING_WORKLOAD = 'training-workload',
  TRAINING_REPORT = 'training-reports',
}
